(defpackage #:cl-rfc8628
  (:nicknames #:rfc8628)
  (:use #:cl)
  (:import-from #:bordeaux-threads
                #:make-lock #:with-lock-held #:make-condition-variable
                #:condition-wait #:condition-notify)
  (:export
   ;; hooks
   #:*device-authentication-error-class*
   #:*device-authentication-redaction-marker*
   #:*device-authentication-timeout*
   #:*rfc8628-device-slow-down-increment*
   #:*secret-region-function*
   #:*user-agent-function*
   ;; support
   #:json-array-p
   #:json-decode
   #:json-encode
   #:json-get
   #:json-object
   #:json-object-p
   #:non-empty-string-p
   #:padded-base64url
   #:redact-exact-string-value
   #:redact-exact-string-values
   #:safe-redaction-marker
   #:unix-time->universal-time
   ;; credentials and store protocol
   #:credential-manager
   #:credential-manager-accept-account
   #:credential-manager-primary-source
   #:managed-credential-manager
   #:credential-manager-account-id
   #:credential-manager-bootstrap-source
   #:credential-manager-provider-label
   #:credential-manager-login-hint
   #:credential-manager-credential-description
   #:credential-manager-refreshable-p
   #:credential-manager-refresh-exchange
   #:credential-manager-import-bootstrap
   #:credential-manager-load
   #:credential-manager-refresh
   #:credential-manager-credentials
   #:credential-manager-newer-rotation
   #:call-with-credentials
   #:with-credentials
   #:credential-error
   #:credential-error-message
   #:credentials-unavailable
   #:credentials-unavailable-searched-paths
   #:token-refresh-failed
   #:token-refresh-failed-status
   #:token-refresh-failed-response
   #:*credential-error-class*
   #:*credentials-unavailable-class*
   #:*token-refresh-failed-class*
   #:credential-source
   #:credential-source-label
   #:credential-source-load
   #:credential-source-pathname
   #:credential-source-save
   #:credentials-needs-refresh-p
   #:jwt-expiration
   #:jwt-payload
   #:jwt-subject
   #:oauth-credentials
   #:oauth-credentials-access-token
   #:oauth-credentials-account-id
   #:oauth-credentials-expires-at
   #:oauth-credentials-id-token
   #:oauth-credentials-refresh-token
   #:oauth-credentials-secret-values
   #:oauth-credentials-source-path
   #:oauth-error-code
   ;; device authentication protocol
   #:device-authentication-client
   #:device-authentication-client-clock-function
   #:device-authentication-client-id
   #:device-authentication-client-issuer
   #:device-authentication-client-poll-function
   #:device-authentication-client-poll-timeout
   #:device-authentication-client-request-function
   #:device-authentication-client-sleep-function
   #:device-authentication-client-browser-function
   #:device-authentication-complete
   #:device-authentication-display-code
   #:device-authentication-error
   #:device-authentication-error-code
   #:device-authentication-error-message
   #:device-authentication-error-stage
   #:device-authentication-error-status
   #:device-authentication-fail
   #:device-authentication-error-code-of-body
   #:device-authentication-invoke-request
   #:device-authentication-issuer-url
   #:device-authentication-json-request
   #:device-authentication-login
   #:device-authentication-monotonic-seconds
   #:device-authentication-open-browser
   #:device-authentication-poll-interval
   #:device-authentication-request
   #:device-authentication-request-code
   #:device-authentication-success-status-p
   #:device-authentication-user-agent
   #:device-authorization
   #:device-authorization-id
   #:device-authorization-poll-interval
   #:device-authorization-user-code
   #:device-authorization-verification-url
   ;; the RFC 8628 flow
   #:rfc8628-device-authentication-account-id
   #:rfc8628-device-authentication-authorization-class
   #:rfc8628-device-authentication-client
   #:rfc8628-device-authentication-client-device-code-path
   #:rfc8628-device-authentication-client-request-code-parameters
   #:rfc8628-device-authentication-client-scope
   #:rfc8628-device-authentication-client-token-path
   #:rfc8628-device-authentication-poll-for-tokens
   #:rfc8628-device-authentication-publish-credentials
   #:rfc8628-device-authentication-validate-token-response
   #:rfc8628-device-authorization
   #:rfc8628-device-authorization-expires-in
   #:rfc8628-device-authorization-issued-at))
